-- Contas (Multi-tenant)
CREATE TABLE contas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Usuários
CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  conta_id BIGINT NOT NULL REFERENCES contas(id),
  papel TEXT NOT NULL DEFAULT 'gestor',
  session_token TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Fornecedores
CREATE TABLE fornecedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  user_id BIGINT NOT NULL REFERENCES usuarios(id),
  ativo INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Peças
CREATE TABLE pecas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number TEXT,
  nome TEXT NOT NULL,
  descricao TEXT,
  user_id BIGINT NOT NULL REFERENCES usuarios(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_pecas_part_number_user ON pecas(part_number, user_id);

-- Etapas das Peças
CREATE TABLE etapas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  ordem INTEGER NOT NULL,
  peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pedidos
CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peca_id BIGINT NOT NULL REFERENCES pecas(id),
  user_id BIGINT NOT NULL REFERENCES usuarios(id),
  fornecedor_id BIGINT NOT NULL REFERENCES fornecedores(id),
  quantidade NUMERIC NOT NULL DEFAULT 1,
  data_entrega TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'Em andamento',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Etapas do Pedido
CREATE TABLE etapas_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  ordem INTEGER NOT NULL,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'Pendente',
  comprovante_url TEXT,
  is_aprovado BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Desenhos Técnicos (Novo formato para Supabase Storage)
CREATE TABLE desenhos_tecnicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peca_id BIGINT NOT NULL REFERENCES pecas(id) ON DELETE CASCADE,
  nome_arquivo TEXT NOT NULL,
  url TEXT NOT NULL, -- URL pública do Supabase Storage
  tipo_arquivo TEXT NOT NULL,
  tamanho INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Storage Bucket Policy (Exemplo - precisa ser configurado no painel do Supabase)
-- insert into storage.buckets (id, name, public) values ('desenhos', 'desenhos', true);
