-- Schema Completo para Migração Final (Inclui tabelas de auditoria e notificações)

-- Tabela de Notificações do Sistema
CREATE TABLE IF NOT EXISTS notificacoes_sistema (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  pedido_id BIGINT REFERENCES pedidos(id) ON DELETE SET NULL,
  tipo TEXT NOT NULL,
  titulo TEXT NOT NULL,
  mensagem TEXT NOT NULL,
  lida BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Evidências Recentes (Auditoria)
CREATE TABLE IF NOT EXISTS evidencias_recentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  tipo TEXT,
  url TEXT,
  descricao TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Histórico de Mudanças de Status (Auditoria)
CREATE TABLE IF NOT EXISTS status_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  status_anterior TEXT,
  status_novo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir que a coluna de configurações do usuário existe
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'usuarios' AND column_name = 'auto_create_pecas_on_import') THEN
    ALTER TABLE usuarios ADD COLUMN auto_create_pecas_on_import BOOLEAN DEFAULT FALSE;
  END IF;
END $$;
